
 
// export default function MyApp({ Component, pageProps }) {
//   return (
//     <div>
 {/* <Navbar user={{ userType: 'Condominios' }} /> */}
//       <Component {...pageProps} />
//     </div>

//   )
// }


import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from '../../components/Navbar'

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-white" >
            <Navbar user={{ userType: 'Condominios' }} />
                {children}
    </div>
  );
}
